//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketManagement.WinForms.STServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SieuthiDTO", Namespace="http://schemas.datacontract.org/2004/07/SupermarketManagement.WCF")]
    [System.SerializableAttribute()]
    public partial class SieuthiDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaSTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SdtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaST {
            get {
                return this.MaSTField;
            }
            set {
                if ((object.ReferenceEquals(this.MaSTField, value) != true)) {
                    this.MaSTField = value;
                    this.RaisePropertyChanged("MaST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sdt {
            get {
                return this.SdtField;
            }
            set {
                if ((object.ReferenceEquals(this.SdtField, value) != true)) {
                    this.SdtField = value;
                    this.RaisePropertyChanged("Sdt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenST {
            get {
                return this.TenSTField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSTField, value) != true)) {
                    this.TenSTField = value;
                    this.RaisePropertyChanged("TenST");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="STServiceReference.ISieuThiService")]
    public interface ISieuThiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/GetAll", ReplyAction="http://tempuri.org/ISieuThiService/GetAllResponse")]
        SupermarketManagement.WinForms.STServiceReference.SieuthiDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/GetAll", ReplyAction="http://tempuri.org/ISieuThiService/GetAllResponse")]
        System.Threading.Tasks.Task<SupermarketManagement.WinForms.STServiceReference.SieuthiDTO[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/GetById", ReplyAction="http://tempuri.org/ISieuThiService/GetByIdResponse")]
        SupermarketManagement.WinForms.STServiceReference.SieuthiDTO GetById(string maST);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/GetById", ReplyAction="http://tempuri.org/ISieuThiService/GetByIdResponse")]
        System.Threading.Tasks.Task<SupermarketManagement.WinForms.STServiceReference.SieuthiDTO> GetByIdAsync(string maST);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/Insert", ReplyAction="http://tempuri.org/ISieuThiService/InsertResponse")]
        bool Insert(SupermarketManagement.WinForms.STServiceReference.SieuthiDTO sieuthi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/Insert", ReplyAction="http://tempuri.org/ISieuThiService/InsertResponse")]
        System.Threading.Tasks.Task<bool> InsertAsync(SupermarketManagement.WinForms.STServiceReference.SieuthiDTO sieuthi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/Update", ReplyAction="http://tempuri.org/ISieuThiService/UpdateResponse")]
        bool Update(SupermarketManagement.WinForms.STServiceReference.SieuthiDTO sieuthi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/Update", ReplyAction="http://tempuri.org/ISieuThiService/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(SupermarketManagement.WinForms.STServiceReference.SieuthiDTO sieuthi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/Search", ReplyAction="http://tempuri.org/ISieuThiService/SearchResponse")]
        SupermarketManagement.WinForms.STServiceReference.SieuthiDTO[] Search(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/Search", ReplyAction="http://tempuri.org/ISieuThiService/SearchResponse")]
        System.Threading.Tasks.Task<SupermarketManagement.WinForms.STServiceReference.SieuthiDTO[]> SearchAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/Delete", ReplyAction="http://tempuri.org/ISieuThiService/DeleteResponse")]
        bool Delete(string maST);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISieuThiService/Delete", ReplyAction="http://tempuri.org/ISieuThiService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string maST);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISieuThiServiceChannel : SupermarketManagement.WinForms.STServiceReference.ISieuThiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SieuThiServiceClient : System.ServiceModel.ClientBase<SupermarketManagement.WinForms.STServiceReference.ISieuThiService>, SupermarketManagement.WinForms.STServiceReference.ISieuThiService {
        
        public SieuThiServiceClient() {
        }
        
        public SieuThiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SieuThiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SieuThiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SieuThiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SupermarketManagement.WinForms.STServiceReference.SieuthiDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<SupermarketManagement.WinForms.STServiceReference.SieuthiDTO[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public SupermarketManagement.WinForms.STServiceReference.SieuthiDTO GetById(string maST) {
            return base.Channel.GetById(maST);
        }
        
        public System.Threading.Tasks.Task<SupermarketManagement.WinForms.STServiceReference.SieuthiDTO> GetByIdAsync(string maST) {
            return base.Channel.GetByIdAsync(maST);
        }
        
        public bool Insert(SupermarketManagement.WinForms.STServiceReference.SieuthiDTO sieuthi) {
            return base.Channel.Insert(sieuthi);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAsync(SupermarketManagement.WinForms.STServiceReference.SieuthiDTO sieuthi) {
            return base.Channel.InsertAsync(sieuthi);
        }
        
        public bool Update(SupermarketManagement.WinForms.STServiceReference.SieuthiDTO sieuthi) {
            return base.Channel.Update(sieuthi);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(SupermarketManagement.WinForms.STServiceReference.SieuthiDTO sieuthi) {
            return base.Channel.UpdateAsync(sieuthi);
        }
        
        public SupermarketManagement.WinForms.STServiceReference.SieuthiDTO[] Search(string keyword) {
            return base.Channel.Search(keyword);
        }
        
        public System.Threading.Tasks.Task<SupermarketManagement.WinForms.STServiceReference.SieuthiDTO[]> SearchAsync(string keyword) {
            return base.Channel.SearchAsync(keyword);
        }
        
        public bool Delete(string maST) {
            return base.Channel.Delete(maST);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string maST) {
            return base.Channel.DeleteAsync(maST);
        }
    }
}
